const EXPO_PUBLIC_SUPABASE_URL =
    process.env.EXPO_PUBLIC_SUPABASE_URL || "";
const EXPO_PUBLIC_SUPABASE_ANON_KEY =
    process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY || "";
const EXPO_PUBLIC_API_URL = process.env.EXPO_PUBLIC_API_URL || "";
const  EXPO_PUBLIC_ANDROID_EMULATOR_URL = process.env.EXPO_PUBLIC_ANDROID_EMULATOR_URL || "";
const EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY = process.env.EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY || "";

export {
    EXPO_PUBLIC_SUPABASE_URL,
    EXPO_PUBLIC_SUPABASE_ANON_KEY,
    EXPO_PUBLIC_API_URL,
    EXPO_PUBLIC_ANDROID_EMULATOR_URL,
    EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY,
};
